/**
 * Night Power - Specialized Health & Sexual Wellness Product Data
 * Prices are in PKR
 */

const defaultProducts = [
    // --- PERFORMANCE SUPPORT ---
    {
        id: 5,
        name: "Titan Grade Performance Gel",
        category: "Performance Support",
        price: 2500,
        originalPrice: 3500,
        image: "images/titan-gel.png",
        description: "A fast-acting topical gel designed to enhance performance and endurance instantly. Dermatologically tested and completely skin-safe.",
        shortDescription: "Fast-acting performance gel.",
        rating: 4.8,
        reviews: 156,
        isTrending: true,
        isNew: false,
        inStock: true,
        discount: "-28%"
    },
    {
        id: 6,
        name: "NightPower Endurance Capsules",
        category: "Performance Support",
        price: 4200,
        originalPrice: 5500,
        image: "images/nightpower-capsules.png",
        description: "Scientifically formulated capsules containing natural adaptogens designed to push your endurance to the absolute limit.",
        shortDescription: "Long-lasting power and endurance.",
        rating: 4.9,
        reviews: 240,
        isTrending: true,
        isNew: false,
        inStock: true,
        discount: "-23%"
    },
    {
        id: 7,
        name: "Pro-Long Delay Spray",
        category: "Performance Support",
        price: 1800,
        originalPrice: 2400,
        image: "https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&w=800",
        description: "Discrete, easy-to-use desensitizing spray that significantly extends your performance time and builds ultimate confidence.",
        shortDescription: "Extend performance time naturally.",
        rating: 4.7,
        reviews: 320,
        isTrending: true,
        isNew: true,
        inStock: true,
        discount: "-25%"
    },
    {
        id: 8,
        name: "Power Surge Energy Tablets",
        category: "Performance Support",
        price: 2800,
        originalPrice: 3400,
        image: "https://images.unsplash.com/photo-1584362917165-526a968579e8?auto=format&fit=crop&w=800",
        description: "Rapid-dissolve tablets packed with B-vitamins and herbal energizers for a massive pre-performance boost.",
        shortDescription: "Rapid pre-performance boost.",
        rating: 4.5,
        reviews: 110,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-17%"
    },

    // --- VITALITY & ENERGY ---
    {
        id: 17,
        name: "Ultra-Vite Daily Multi-Vitamin",
        category: "Vitality & Energy",
        price: 3200,
        originalPrice: 3800,
        image: "https://images.unsplash.com/photo-1616671285410-6c0b93ca88e6?auto=format&fit=crop&w=800",
        description: "Comprehensive daily multivitamin specifically engineered for high-energy lifestyles. Supports immune health and metabolic function.",
        shortDescription: "Daily multivitamin for energy.",
        rating: 4.8,
        reviews: 85,
        isTrending: false,
        isNew: true,
        inStock: true,
        discount: "-15%"
    },
    {
        id: 18,
        name: "GTI Power Energy Gel",
        category: "Vitality & Energy",
        price: 1500,
        originalPrice: 2000,
        image: "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=800",
        description: "Instant energy gel for athletes and active individuals. Provides a rapid carbohydrate boost and electrolyte balance.",
        shortDescription: "Instant energy for active lifestyles.",
        rating: 4.6,
        reviews: 64,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-25%"
    },
    {
        id: 19,
        name: "Advanced B-Complex Syrup",
        category: "Vitality & Energy",
        price: 1200,
        originalPrice: 1500,
        image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=800",
        description: "High-absorption liquid B-complex to improve focus, reduce fatigue, and support a healthy nervous system.",
        shortDescription: "Liquid B-complex for mental focus.",
        rating: 4.7,
        reviews: 42,
        isTrending: false,
        isNew: true,
        inStock: true,
        discount: "-20%"
    },
    {
        id: 20,
        name: "Peak Performance Coffee Booster",
        category: "Vitality & Energy",
        price: 2400,
        originalPrice: 3000,
        image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800",
        description: "Turn your morning coffee into a metabolic powerhouse. Enhances caffeine effects while preventing the typical crash.",
        shortDescription: "Enhance your morning energy.",
        rating: 4.5,
        reviews: 38,
        isTrending: true,
        isNew: false,
        inStock: true,
        discount: "-20%"
    },

    // --- MEN'S WELLNESS ---
    {
        id: 1,
        name: "Tribal Testo-Boost Formula",
        category: "Men's Wellness",
        price: 4800,
        originalPrice: 6000,
        image: "https://images.unsplash.com/photo-1579722820308-d74e571900a9?auto=format&fit=crop&w=800",
        description: "Natural testosterone support designed to improve strength, muscle mass, and overall masculine health securely and safely.",
        shortDescription: "Support masculine health naturally.",
        rating: 4.8,
        reviews: 180,
        isTrending: true,
        isNew: false,
        inStock: true,
        discount: "-20%"
    },
    {
        id: 2,
        name: "Alpha Male Vitality Complex",
        category: "Men's Wellness",
        price: 5200,
        originalPrice: 6500,
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800",
        description: "A premium blend of minerals and vitamins formulated to maximize focus, vitality, and daily male energy levels.",
        shortDescription: "Maximize male energy and focus.",
        rating: 4.9,
        reviews: 215,
        isTrending: true,
        isNew: true,
        inStock: true,
        discount: "-20%"
    },
    {
        id: 25,
        name: "Prostate Health Support",
        category: "Men's Wellness",
        price: 3900,
        originalPrice: 4500,
        image: "https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?auto=format&fit=crop&w=800",
        description: "Natural formula containing Saw Palmetto and Zinc to support healthy prostate function and urinary flow.",
        shortDescription: "Support for healthy prostate function.",
        rating: 4.7,
        reviews: 56,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-13%"
    },
    {
        id: 26,
        name: "Masculine Follicle Fortifier",
        category: "Men's Wellness",
        price: 4500,
        originalPrice: 5500,
        image: "https://images.unsplash.com/photo-1626015401419-f521c7847702?auto=format&fit=crop&w=800",
        description: "Advanced hair thickening formula with biotin and saw palmetto specifically targeted for male-pattern concerns.",
        shortDescription: "Thickening formula for male hair.",
        rating: 4.6,
        reviews: 72,
        isTrending: true,
        isNew: true,
        inStock: true,
        discount: "-18%"
    },

    // --- WOMEN'S WELLNESS ---
    {
        id: 13,
        name: "Female Passion Support Drops",
        category: "Women's Wellness",
        price: 2900,
        originalPrice: 3800,
        image: "https://images.unsplash.com/photo-1611080626919-7cf5a969fc8f?auto=format&fit=crop&w=800",
        description: "A premium, natural formula designed to support female vitality and passion. Infused with herbal extracts that promote hormonal balance.",
        shortDescription: "Premium natural drops for women.",
        rating: 4.8,
        reviews: 112,
        isTrending: true,
        isNew: true,
        inStock: true,
        discount: "-23%"
    },
    {
        id: 14,
        name: "Evening Primrose Oil Softgels",
        category: "Women's Wellness",
        price: 2200,
        originalPrice: 2800,
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800",
        description: "Rich in GLA to support clear skin, ease discomfort, and balance hormones smoothly from the inside out.",
        shortDescription: "Hormone balance and skin health.",
        rating: 4.7,
        reviews: 165,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-21%"
    },
    {
        id: 15,
        name: "Hormone Balance Complex",
        category: "Women's Wellness",
        price: 3600,
        originalPrice: 4500,
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800",
        description: "An advanced multivitamin and mineral blend specifically tailored to correct imbalances and support female reproductive wellness.",
        shortDescription: "Advanced reproductive wellness blend.",
        rating: 4.9,
        reviews: 94,
        isTrending: false,
        isNew: true,
        inStock: true,
        discount: "-20%"
    },
    {
        id: 16,
        name: "Radiant Skin Glow Capsules",
        category: "Women's Wellness",
        price: 4200,
        originalPrice: 5000,
        image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=800",
        description: "Marine collagen and hyaluronic acid complex for youthful skin, stronger hair, and vibrant nails.",
        shortDescription: "Collagen complex for skin and hair.",
        rating: 4.8,
        reviews: 124,
        isTrending: true,
        isNew: true,
        inStock: true,
        discount: "-16%"
    },

    // --- NATURAL HERBAL ---
    {
        id: 9,
        name: "Pure Himalayan Shilajit (Med Grade)",
        category: "Natural Herbal",
        price: 5500,
        originalPrice: 7000,
        image: "images/shilajit-resin.png",
        description: "Authentic Himalayan Shilajit resin, rich in fulvic acid and 84+ minerals for holistic wellness, vigor, and immune support.",
        shortDescription: "Holistic vigor from the Himalayas.",
        rating: 4.9,
        reviews: 310,
        isTrending: true,
        isNew: false,
        inStock: true,
        discount: "-21%"
    },
    {
        id: 10,
        name: "Royal Ginseng Vitality Extract",
        category: "Natural Herbal",
        price: 3800,
        originalPrice: 4800,
        image: "images/ginseng-extract.png",
        description: "Pure Korean Red Ginseng extract for a natural energy boost, improved mental clarity, and fortified immunity.",
        shortDescription: "Energy from natural ginseng.",
        rating: 4.7,
        reviews: 112,
        isTrending: false,
        isNew: true,
        inStock: true,
        discount: "-20%"
    },
    {
        id: 11,
        name: "Daily Zinc & Ashwagandha Complex",
        category: "Natural Herbal",
        price: 2600,
        originalPrice: 3200,
        image: "https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?auto=format&fit=crop&w=800",
        description: "The ultimate daily defense blend. Ashwagandha fights stress while Zinc supports critical reproductive health systems.",
        shortDescription: "Daily stress and reproductive support.",
        rating: 4.8,
        reviews: 145,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-18%"
    },
    {
        id: 12,
        name: "Organic Tongkat Ali Powder",
        category: "Natural Herbal",
        price: 4100,
        originalPrice: 4800,
        image: "https://images.unsplash.com/photo-1596649830500-1c586144e548?auto=format&fit=crop&w=800",
        description: "Premium sourced root powder used for centuries to elevate mood, stamina, and masculine drive. Easy to mix into drinks.",
        shortDescription: "Elevate stamina and drive.",
        rating: 4.6,
        reviews: 89,
        isTrending: false,
        isNew: true,
        inStock: true,
        discount: "-14%"
    },

    // --- INTIMATE CARE ---
    {
        id: 21,
        name: "Ultra-Soothe Intimate Massage Oil",
        category: "Intimate Care",
        price: 2000,
        originalPrice: 2800,
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800",
        description: "Premium pH-balanced massage oil with essential oils for a relaxing and smooth intimate experience. Leaves skin feeling silky.",
        shortDescription: "Relaxing intimate massage experience.",
        rating: 4.5,
        reviews: 128,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-28%"
    },
    {
        id: 22,
        name: "VelvetTouch Premium Lubricant",
        category: "Intimate Care",
        price: 1500,
        originalPrice: 2000,
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800",
        description: "Water-based, long-lasting premium lubricant. Non-sticky formula that feels natural and is perfectly safe for sensitive skin.",
        shortDescription: "Natural feel water-based lubricant.",
        rating: 4.7,
        reviews: 95,
        isTrending: true,
        isNew: true,
        inStock: true,
        discount: "-25%"
    },
    {
        id: 23,
        name: "Gentle PH-Balanced Intimate Wash",
        category: "Intimate Care",
        price: 1800,
        originalPrice: 2400,
        image: "https://images.unsplash.com/photo-1619451334792-150fd785ee74?auto=format&fit=crop&w=800",
        description: "Daily hygiene wash designed to maintain natural PH levels and provide lasting freshness without irritation.",
        shortDescription: "Daily hygiene for sensitive areas.",
        rating: 4.8,
        reviews: 43,
        isTrending: false,
        isNew: true,
        inStock: true,
        discount: "-25%"
    },
    {
        id: 24,
        name: "Silk-Finish Soothing Balm",
        category: "Intimate Care",
        price: 2200,
        originalPrice: 3000,
        image: "https://images.unsplash.com/photo-1498843053639-170ff2122f35?auto=format&fit=crop&w=800",
        description: "Repair and soothe delicate areas with this rich, protective balm. Contains aloe and vitamin E for instant relief.",
        shortDescription: "Protective balm for delicate skin.",
        rating: 4.6,
        reviews: 31,
        isTrending: false,
        isNew: false,
        inStock: true,
        discount: "-26%"
    }
];

let products = JSON.parse(localStorage.getItem('nightpower_products_v3'));

if (!products || products.length === 0) {
    products = defaultProducts;
    localStorage.setItem('nightpower_products_v3', JSON.stringify(products));
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = products;
}
